In [1]:
import numpy as np, math

a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
c = np.inner(a, b)
d = np.inner(b, a)

print( " a = ", a )
print( " b = ", b )
print( " c = ", c )
print( " d = ", d )

print( np.arctan2(3, 3)/math.pi )

print( np.power( 0, 0 ) ) 

 a =  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
 b =  [0 1 2 3]
 c =  [[ 14  38  62]
 [ 86 110 134]]
 d =  [[ 14  38  62]
 [ 86 110 134]]
0.25
1


In [ ]:
if 0 : 
    chart.set_xlim( 0 , t_img.shape[1] - 1 )
    chart.set_ylim( 0 , t_img.shape[0] - 1)
    chart.set_yticks( np.arange( 0, t_img.shape[1]))
    chart.set_yticks( np.arange( 0, t_img.shape[0])[::-1])
    chart.axhline(y=0, color='k')
    chart.axvline(x=0, color='k')

    chart.add_artist( plt.Circle((0, 0), 1, fill=0) )
    chart.scatter( x, y, marker="." )

In [2]:
import pandas as pd

print( pd.__version__ )

a = [ [ 1, 2,3 ] , [ 4, 5, 6 ] ]

pd.DataFrame( a, columns=[ "A", "B", "C" ] )

2.2.0


A  B  C
0  1  2  3
1  4  5  6