In [2]:
import numpy as np, math

a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
c = np.inner(a, b)
d = np.inner(b, a)

print( " a = ", a )
print( " b = ", b )
print( " c = ", c )
print( " d = ", d )

print( np.arctan2(3, 3)/math.pi )

 a =  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
 b =  [0 1 2 3]
 c =  [[ 14  38  62]
 [ 86 110 134]]
 d =  [[ 14  38  62]
 [ 86 110 134]]
0.25
